package com.brotherlogic.proxycache;

import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;

@Retention(RetentionPolicy.RUNTIME)
public @interface LinkURL {

	/**
	 * @return the json path to the actual attribute
	 */
	String path() default "";

	/**
	 * @return The class generated by this method (for dealing with generic
	 *         collections)
	 */
	String prodClass() default "";

	/**
	 * @return A reference to the url which generates this attribute
	 */
	String url() default "";
}
