package com.brotherlogic.proxycache;

import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;

/**
 * Links a method to a url path
 * 
 * @author simon
 * 
 */
@Retention(RetentionPolicy.RUNTIME)
public @interface LinkURL {

    /**
     * The json path to the actual attribute
     */
    String path() default "";

    /**
     * The class generated by this method (for dealing with generic collections)
     */
    String prodClass() default "";

    /**
     * A reference to the url which generates this attribute
     */
    String url() default "";
}
